### ISSUE TITLE
[Bug] Backup  & restore "DATA"  not work.

### ISSUE THREAD

**Issue by Guang1234567** [TeamWin/android_device_oneplus_lemonadep#4]
Hello dev:

1.   boot twrp temporarily

```
Temporary boot the downloaded image using the following command:

fastboot boot twrp-3.6.0_11-0-lemonadep.img
```

2.  then backup  "DATA"

3. restore "DATA" from backup

4. the device cannot enter the launcher,  always play boot animation loop

Thanks.

**Comment by Guang1234567** [comment]
- log

```
01-22 16:25:54.802  2064  2086 I BootAnimation: check exit :
01-22 16:25:55.483  1932  2042 W ActivityManager: Process ProcessRecord{c675a69 4118:com.heytap.cloud/u0a229} failed to attach
01-22 16:25:55.484  1932  2042 I ActivityManager: Killing 4118:com.heytap.cloud/u0a229 (adj -10000): start timeout
01-22 16:25:55.457  2064  2086 I chatty  : uid=1000(system) BootAnimation identical 39 lines
01-22 16:25:55.474  2064  2086 I BootAnimation: check exit :
01-22 16:25:55.484  1932  2042 W Process : Unable to open /proc/4118/status
01-22 16:25:55.484  1932  2042 W ActivityManager: Unattached app died before broadcast acknowledged, skipping
01-22 16:25:55.484  1932  2049 I OplusStorageAllFileAccessManager: checkAppWhitelist: packageName com.heytap.cloud, mode 2
01-22 16:25:55.484  1932  2049 I OplusStorageAllFileAccessManager: SignedWithPrivateKey, package:com.heytap.cloud, check hash result=true
01-22 16:25:55.484  1932  2042 W ActivityManager: Unattached app died before broadcast acknowledged, skipping
01-22 16:25:55.490  1932  2043 I ActivityManager: Start proc 4137:com.heytap.cloud/u0a229 for broadcast {com.heytap.cloud/com.cloud.base.commonsdk.receiver.SyncDataChangedReceiver}
01-22 16:25:55.491  2064  2086 I BootAnimation: check exit :
01-22 16:25:55.491  4137  4137 F zygote64: jni_internal.cc:729] JNI FatalError called: (com.heytap.cloud) frameworks/base/core/jni/com_android_internal_os_Zygote.cpp:1290: Unable to find com.heytap.cloud:100089 in /data_mirror/data_ce/null/0
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655] Runtime aborting...
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655] Dumping all threads without mutator lock held
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655] All threads:
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655] DALVIK THREADS (1):
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655] "main" prio=5 tid=1 Runnable
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   | group="" sCount=0 dsCount=0 flags=0 obj=0x732c09d8 self=0xb400007323210800
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   | sysTid=860 nice=0 cgrp=default sched=0/0 handle=0x73aabf2500
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   | state=? schedstat=( 0 0 0 ) utm=0 stm=0 core=0 HZ=100
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   | stack=0x7fe6997000-0x7fe6999000 stackSize=8192KB
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   | held mutexes= "abort lock" "mutator lock"(shared held)
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   native: (backtrace::Unwind failed for thread 860: Thread doesn't exist)
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   at com.android.internal.os.Zygote.nativeForkAndSpecialize(Native method)
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   at com.android.internal.os.Zygote.forkAndSpecialize(Zygote.java:358)
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   at com.android.internal.os.ZygoteConnection.processOneCommand(ZygoteConnection.java:257)
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   at com.android.internal.os.ZygoteServer.runSelectLoop(ZygoteServer.java:546)
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:993)
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655] Aborting thread:
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655] "main" prio=5 tid=1 Native
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   | group="" sCount=0 dsCount=0 flags=0 obj=0x732c09d8 self=0xb400007323210800
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   | sysTid=860 nice=0 cgrp=default sched=0/0 handle=0x73aabf2500
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   | state=? schedstat=( 0 0 0 ) utm=0 stm=0 core=0 HZ=100
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   | stack=0x7fe6997000-0x7fe6999000 stackSize=8192KB
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   | held mutexes= "abort lock"
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   native: (backtrace::Unwind failed for thread 860: Thread doesn't exist)
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   at com.android.internal.os.Zygote.nativeForkAndSpecialize(Native method)
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   at com.android.internal.os.Zygote.forkAndSpecialize(Zygote.java:358)
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   at com.android.internal.os.ZygoteConnection.processOneCommand(ZygoteConnection.java:257)
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   at com.android.internal.os.ZygoteServer.runSelectLoop(ZygoteServer.java:546)
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:993)
01-22 16:25:55.496  4137  4137 F zygote64: runtime.cc:655]
01-22 16:25:55.497  4137  4137 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 4137 (main), pid 4137 (main)
01-22 16:25:55.500  4144  4144 E libc    : capset failed: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 0: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 1: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 2: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 3: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 4: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 5: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 6: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 7: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 8: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 9: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 10: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 11: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 12: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 13: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 14: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 15: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 16: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 17: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 18: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 19: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 20: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 21: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 22: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 23: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 24: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 25: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 26: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 27: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 28: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 29: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 30: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 31: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 32: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 33: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 34: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 35: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 36: Operation not permitted
01-22 16:25:55.500  4144  4144 E libc    : failed to raise ambient capability 37: Operation not permitted
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/0: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/1: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/2: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/3: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/4: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/5: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/6: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/7: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/8: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/9: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/10: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/11: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/12: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/13: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/14: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/15: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/16: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/17: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/18: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/19: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/20: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/21: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/22: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/23: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/24: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/25: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/26: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/27: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/28: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/29: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/30: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/31: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/32: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/33: Permission denied
01-22 16:25:55.506  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/34: Permission denied
01-22 16:25:55.507  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/35: Permission denied
01-22 16:25:55.507  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/36: Permission denied
01-22 16:25:55.507  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/37: Permission denied
01-22 16:25:55.507  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/38: Permission denied
01-22 16:25:55.507  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/39: Permission denied
01-22 16:25:55.507  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/40: Permission denied
01-22 16:25:55.507  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/41: Permission denied
01-22 16:25:55.507  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/42: Permission denied
01-22 16:25:55.507  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/43: Permission denied
01-22 16:25:55.507  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/44: Permission denied
01-22 16:25:55.507  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/45: Permission denied
01-22 16:25:55.507  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/46: Permission denied
01-22 16:25:55.507  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/47: Permission denied
01-22 16:25:55.507  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/48: Permission denied
01-22 16:25:55.507  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/49: Permission denied
01-22 16:25:55.507  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/50: Permission denied
01-22 16:25:55.507  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/51: Permission denied
01-22 16:25:55.507  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/52: Permission denied
01-22 16:25:55.507  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/53: Permission denied
01-22 16:25:55.507  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/54: Permission denied
01-22 16:25:55.507  4145  4145 E DEBUG   : failed to readlink /proc/4137/fd/55: Permission denied
01-22 16:25:55.507  4145  4145 F crash_dump64: crash_dump.cpp:479] failed to attach to thread 4137, already traced by 0 ()
```
